export const NIGERIAN_CAMPUSES = [
  // Universities - Federal
  "University of Lagos (UNILAG)",
  "University of Ibadan (UI)",
  "Obafemi Awolowo University (OAU)",
  "Ahmadu Bello University (ABU)",
  "University of Nigeria, Nsukka (UNN)",
  "University of Benin (UNIBEN)",
  "University of Ilorin (UNILORIN)",
  "University of Port Harcourt (UNIPORT)",
  "University of Maiduguri (UNIMAID)",
  "University of Calabar (UNICAL)",
  "University of Jos (UNIJOS)",
  "University of Abuja (UNIABUJA)",
  "University of Uyo (UNIUYO)",
  "Nnamdi Azikiwe University (UNIZIK)",
  "Bayero University Kano (BUK)",
  "Federal University of Technology, Akure (FUTA)",
  "Federal University of Technology, Minna (FUTMINNA)",
  "Federal University of Technology, Owerri (FUTO)",
  "Federal University of Agriculture, Abeokuta (FUNAAB)",
  "Federal University of Agriculture, Makurdi (FUAM)",
  "Michael Okpara University of Agriculture, Umudike (MOUAU)",
  "Federal University, Lokoja",
  "Federal University, Lafia",
  "Federal University, Kashere",
  "Federal University, Wukari",
  "Federal University, Dutsin-Ma",
  "Federal University, Dutse",
  "Federal University, Ndufu-Alike",
  "Federal University, Oye-Ekiti",
  "Federal University, Otuoke",
  "Federal University, Birnin Kebbi",
  "Federal University, Gusau",
  "Federal University, Gashua",
  "Federal University of Petroleum Resources, Effurun (FUPRE)",
  "Federal University of Technology, Babura",
  "Federal University of Technology, Ikot Abasi",
  "Federal University of Health Sciences, Otukpo",
  "Federal University of Health Sciences, Azare",
  "Federal University of Health Sciences, Ila-Orangun",
  "Nigeria Defence Academy (NDA)",
  "Police Academy, Wudil",

  // Universities - State
  "Lagos State University (LASU)",
  "Ladoke Akintola University of Technology (LAUTECH)",
  "Ekiti State University (EKSU)",
  "Olabisi Onabanjo University (OOU)",
  "Rivers State University (RSU)",
  "Delta State University (DELSU)",
  "Enugu State University of Science and Technology (ESUT)",
  "Ambrose Alli University (AAU)",
  "Kwara State University (KWASU)",
  "Adekunle Ajasin University (AAUA)",
  "Osun State University (UNIOSUN)",
  "Abia State University (ABSU)",
  "Imo State University (IMSU)",
  "Benue State University (BSU)",
  "Kaduna State University (KASU)",
  "Plateau State University (PLASU)",
  "Bauchi State University (BASUG)",
  "Gombe State University (GSU)",
  "Yobe State University (YSU)",
  "Nasarawa State University (NSUK)",
  "Kogi State University (KSU)",
  "Niger State University",
  "Taraba State University",
  "Adamawa State University (ADSU)",
  "Sokoto State University",
  "Kebbi State University of Science and Technology (KSUSTA)",
  "Kano University of Science and Technology (KUST)",
  "Tai Solarin University of Education (TASUED)",
  "Ignatius Ajuru University of Education (IAUE)",

  // Universities - Private
  "Covenant University",
  "Babcock University",
  "Afe Babalola University (ABUAD)",
  "Bowen University",
  "Pan-Atlantic University",
  "American University of Nigeria (AUN)",
  "Baze University",
  "Nile University of Nigeria",
  "Redeemer's University",
  "Landmark University",
  "Bells University of Technology",
  "Ajayi Crowther University",
  "Lead City University",
  "Bingham University",
  "Veritas University",
  "Madonna University",
  "Igbinedion University",
  "Gregory University",
  "Skyline University Nigeria",
  "Augustine University",
  "Mountain Top University",
  "Chrisland University",
  "McPherson University",
  "Anchor University",
  "Hallmark University",
  "Southwestern University",

  // Polytechnics
  "Yaba College of Technology (YABATECH)",
  "Lagos State Polytechnic (LASPOTECH)",
  "Federal Polytechnic, Ilaro",
  "Federal Polytechnic, Nekede",
  "Federal Polytechnic, Ado-Ekiti",
  "Federal Polytechnic, Offa",
  "Federal Polytechnic, Ede",
  "Federal Polytechnic, Bauchi",
  "Federal Polytechnic, Bida",
  "Federal Polytechnic, Idah",
  "Federal Polytechnic, Oko",
  "Federal Polytechnic, Mubi",
  "Federal Polytechnic, Nasarawa",
  "Federal Polytechnic, Bali",
  "Federal Polytechnic, Ekowe",
  "Federal Polytechnic, Kaura Namoda",
  "Kaduna Polytechnic",
  "Auchi Polytechnic",
  "The Polytechnic, Ibadan",
  "Moshood Abiola Polytechnic (MAPOLY)",
  "Kwara State Polytechnic",
  "Petroleum Training Institute (PTI)",
  "Ramat Polytechnic",
  "Abia State Polytechnic",
  "Imo State Polytechnic",
  "Delta State Polytechnic, Ogwashi-Uku",
  "Delta State Polytechnic, Otefe-Oghara",
  "Delta State Polytechnic, Ozoro",
  "Gateway ICT Polytechnic",
  "Abraham Adesanya Polytechnic",

  // Colleges of Education
  "Federal College of Education (Technical), Akoka",
  "Adeyemi College of Education",
  "Federal College of Education, Abeokuta",
  "Federal College of Education, Kano",
  "Federal College of Education, Zaria",
  "Federal College of Education, Okene",
  "Federal College of Education, Pankshin",
  "Federal College of Education, Kontagora",
  "Federal College of Education, Katsina",
  "Federal College of Education, Obudu",
  "Federal College of Education, Eha-Amufu",
  "Lagos State College of Education (AOCOED)",
  "Tai Solarin College of Education",
  "College of Education, Ikere-Ekiti",
  "College of Education, Warri",
  "College of Education, Agbor",

  // Nursing & Health Schools
  "Lagos State College of Nursing (LASCON)",
  "School of Nursing, University College Hospital (UCH)",
  "School of Nursing, LUTH",
  "School of Nursing, UNTH",
  "Oyo State College of Nursing and Midwifery",
  "Ogun State School of Nursing",
  "College of Health Technology, Yaba",
  "College of Health Technology, Offa",
  "College of Health Technology, Calabar",
  "School of Nursing, AKTH",
  "School of Nursing, ABUTH",
  "School of Nursing, JUTH",

  // Technical Schools
  "Government Technical College, Ikorodu",
  "Government Technical College, Ado-Soba",
  "Government Technical College, Odomola",
  "Government Technical College, Agidingbi",
  "Federal Science and Technical College (FSTC), Yaba",
  "Federal Science and Technical College (FSTC), Ilesa",
  "Federal Science and Technical College (FSTC), Awka"
].sort();
